<?php
/**
 * Promo view template
 *
 * @var $block \Packt\Promo\Block\Promo
 */
$getimg = $block->getImage();
// $productCollection = $block->getCategoryProducts(8);
$mediaUrl = $block->getProductUrlImage();
?>
<!-- <h1 style="text-align:center;"><//?php echo $block->getTitle(); ?></h1> -->
<div class="wrapper">
<div class="jcarousel-wrapper">
    <div class="jcarousel">
        <ul>
            <?php
// foreach ($productCollection as $product) {
//     echo '<li><img src="' . $mediaUrl . $product->getData()['small_image'] . '" alt="Image 1"></li>';
// }
// foreach ($getimg as $productimg) {
//     echo '<li><img src="' . $mediaUrl . $productimg->getData()['small_image'] . '" alt="Image 1"></li>';
$blockHtml = $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('slider')->toHtml();
// echo $block->escapeHtml($blockHtml);
echo $blockHtml;

?>
        </ul>
        </div>
            <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
            <a href="#" class="jcarousel-control-next">&rsaquo;</a>
            <p class="jcarousel-pagination"></p>
        </div>
    </div>
<!-- <div data-mage-init='{"hello": {"message": "HELLO WORLD!"}}'>
</div> -->
<script>
requirejs(['promo'], function(promo){
promo.promoBlock('.jcarousel', '.jcarousel-control-prev', '.jcarousel-control-next', '.jcarousel-pagination');
});
</script>
