<!-- <header>
    <div class="container-fluid header_top">
        <div class="header_top_left">
            <i class="far fa-bookmark"></i>
            <span>Welcome to Franco - an e-Commerce PSD Template!</span>
        </div>
        <div class="header_top_right">
            <a href=""><i class="fas fa-lock"></i> <span>Shop Setting</span></a>
            <a href=""><i class="fas fa-cog"></i><span>Member Login</span></a>
        </div>
    </div>
    <div class="container-fluid header_bottom">
        <div class="row">
            <div class="col-lg-12">
                <nav class="navbar navbar-expand-lg navbar-light">
                    <a class="navbar-branch" href="#">
                        <img src="assets/images/logo.jpg" class="image">
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse sub-menu-bar" id="navbarSupportedContent">
                        <ul id="nav" class="navbar-nav m-auto">
                            <li class="nav-item active">
                                <a href="#home" class="_active">HOME</a>
                            </li>
                            <li class="nav-item">
                                <a href="#women">WOMEN</a>
                            </li>
                            <li class="nav-item">
                                <a href="#man">MEN</a>
                            </li>
                            <li class="nav-item">
                                <a href="#aboutus">ABOUT US</a>
                            </li>
                            <li class="nav-item">
                                <a href="#blog">BLOG</a>
                            </li>
                            <li class="nav-item">
                                <a href="#colections">COLECTIONS</a>
                            </li>
                            <li class="nav-item">
                                <a href="#contact">CONTACT</a>
                            </li>
                            <li class="nav-item">
                                <a href="#search"><i class="fas fa-search"></i></a>
                            </li>
                        </ul>
                    </div>
                    <div class="navbar-btn d-none d-lg-inline-block ">
                        <i class="fas fa-heart"></i>
                        <i class="fas fa-shopping-cart"></i>
                    </div>
                </nav>
            </div>
        </div>
    </div>
</header> -->
<!-- end header -->

<!-- start banner -->
<!-- <div class="container banner">
    <div class="row">
        <div class="col-lg-8 col-sm-12 banner_left">
            <img src="assets/images/banner1.jpg" alt="">
            <div class="banner_text">
                <p>TwoHight-endMaterials</p>
            </div>
            <a href="http://" class="shop1">Shop Now</a>
        </div>

        <div class="col-lg-4 banner-right">
            <div class="banner_right-top">
                <img src="assets/images/banner2.jpg" alt="">
                <div class="banner_right-top-text">
                    <p>SMALL THING</p>
                    <p>MAKE DIFFERENT</p>
                </div>
            </div>
            <div class="banner_right-bottom">
                <img src="assets/images/banner3.jpg" alt="">
                <div class="banner_right-bottom-text">
                    <p>FOLIO</p>
                    <p>BACKPACK</p>
                </div>
                <a href="" class="shop">Shop Now</a>
            </div>
        </div>
    </div>
</div> -->
<!-- end banner -->

<!-- start product -->
<!-- <div class="container product">
    <p>FRANCO</p>
    <h3>FEATURED ITEMS</h3>
    <div class="product_line"></div>
    <div class="row">
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product1.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product2.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product3.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product4.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product5.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product6.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product7.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-6 col-12">
            <div class="product_detail">
                <img src="assets/images/product8.png" alt="">
                <a href="http://">ADD TO CART</a>
            </div>
            <div class="product_text">
                <a href="">Suspendisse id volutpat</a>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star rate"></i>
                <i class="far fa-star"></i>
                <div class="product_price"><del>$99.80</del><span> $84.00</span></div>
            </div>
        </div>
    </div>
</div> -->
<!-- end product -->

<!-- start blog -->
<!-- <div class="blog">
    <p>LATEST</p>
    <h3>NEWS & EVENTS</h3>
    <div class="blog_line"></div>
    <div class="container owl-carousel owl-theme blog_content">
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
        <div class="item">
            <div class="item_top">
                <img src="assets/images/slider1.png" alt="slider1">
                <img src="assets/images/jan.jpg" alt="slider1">
            </div>
            <div class="item_center">
                <a href="">In Commodo dolor vitae</a>
                <h5>Aliquam tempor sagittis neque, vel qliquam rius consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orci mauris.
                </h5>
            </div>
            <div class="item_bottom">
                <i class="far fa-comment"></i> <span> 12</span>
                <i class="far fa-heart"></i> <span> 6</span>
            </div>
        </div>
    </div>
</div> -->
<!-- end blog -->


<!-- start footer -->
<!-- <footer>
    <div class="container _footer">
        <div class="row">
            <div class="col-lg-3 footer_about">
                <p>About Franco</p>
                <p>Aliquam tempor sagittis neque, vel allquam risus consectetur vel. Aenean hendrerit, elit a lacinia suscipit, orcl mauris vulputate mi, eu interdum nunc diam at ipsum.</p>
                <p>
                    <i class="fab fa-twitter"></i>
                    <i class="fab fa-linkedin-in"></i>
                    <i class="fab fa-behance"></i>
                    <i class="fas fa-basketball-ball"></i>
                </p>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-4 footer_navigation">
                <p>Navigation</p>
                <div class="row">
                    <div class="col-lg-6 col-6 footer_navigation-top">
                        <a href="">Home</a>
                        <a href="">About Us</a>
                        <a href="">Our Blog</a>
                        <a href="">Women</a>
                        <a href="">Man</a>
                        <a href="">Contact Us</a>
                    </div>
                    <div class="col-lg-6 col-6 footer_navigation-top">
                        <a href="">FAQs</a>
                        <a href="">Featured Brands</a>
                        <a href="">Gift Vouchers</a>
                        <a href="">Affiliates</a>
                        <a href="">Specials Gift</a>
                        <a href="">Terms & conditions</a>
                    </div>
                </div>
            </div>
            <div class="col-lg-1"></div>
            <div class="col-lg-3 footer_location">
                <p>Shop Location</p>
                <p>
                    <i class="far fa-map"></i>
                    <span>500 Hennessy Road Causeway Bay, Hong Kong</span>
                </p>
                <p>
                    <i class="fas fa-phone-alt"></i>
                    <span>+1 &nbsp; 23456789</span>
                </p>
                <p>
                    <i class="far fa-envelope"></i>
                    <span>contact@yourdomain.com</span>
                </p>
            </div>
        </div>
    </div>
</footer>
<div class="footer_bottom">
    <div class="container _footer">
        <span>© Copyright 2015 & Made with <i class="fas fa-heart"></i> by <span class="white">Arrowhitech</span></span>
        <span class="_right">
            <i class="fab fa-cc-visa"></i>
            <i class="fab fa-cc-paypal"></i>
            <i class="fab fa-cc-mastercard"></i>
            <i class="fab fa-cc-discover"></i>
            <i class="fab fa-cc-amex"></i>
        </span>
    </div>
</div> -->

<!-- end footer -->
